import BottomNav from '@/components/atoms/BottomNav/BottomNav';
import { Toaster } from '@/components/ui/toaster';
import { NotificationProvider } from '@/providers/NotificationProvider';
import StreamVideoProvider from '@/providers/StreamClientProvider';
import { SessionProvider } from 'next-auth/react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { auth } from '@/lib/auth';
import QueryProviders from './QueryProviders';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang='en'>
      <body
        className={`font-pretendard ${pretendard.variable} antialiased text-black`}
      >
        <QueryProviders>
          <SessionProvider session={session}>
            <NotificationProvider>
              <StreamVideoProvider>
                {children}
                <Toaster />
                <BottomNav />
              </StreamVideoProvider>
            </NotificationProvider>
          </SessionProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
