name: NEXT CI/CD 
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup node pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node
        uses: actions/setup-node@v4
        with:
            node-version: 21
  
      - name: Install dependencies
        run: pnpm install
  
      - name: set .env
        run: |
            echo "${{ secrets.ENV }}" > .env
            
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.WAS }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Build with Next.js
        run: pnpm next build

      - name: zip next = .next아래에 next.zip 이름의 zip 파일 생성
        run: zip -rq next.zip .next

      - name: scp next to was = was에 전송, next.zip을 workspace내에 저장
        run: |
          scp next.zip ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/

      - name: restart next = workspace 아래 client 폴더의 .next 삭제
        run: |
          ssh ec2-user@${{ secrets.WAS }} '
            cd /home/ec2-user/workspace
            rm -rf .next
            unzip next.zip
            pm2 reload sonju-next
          '
